language: node_js
node_js:
    - "node"
install:
    - "yarn install"
script:
    - "yarn build"
deploy:
    - provider: script
      script: sh scripts/deploy.sh
      on:
          branch: master
addons:
    ssh_known_hosts:
        - "breathe.network:50265"
